export const DATA_HOME = [
    { image: '/images/product-01.jpg', quickview: 'Quick View', title: 'Esprit Ruffle Shirt', price: '$16.64', type: 'women' },
    { image: '/images/product-02.jpg', quickview: 'Quick View', title: 'Herschel supply', price: '$35.31', type: 'women' },
    { image: '/images/product-03.jpg', quickview: 'Quick View', title: 'Only Check Trouser', price: '$25.50', type: 'men' },
    { image: '/images/product-04.jpg', quickview: 'Quick View', title: 'Classic Trench Coat', price: '$75.00', type: 'women' },
    { image: '/images/product-05.jpg', quickview: 'Quick View', title: 'Front Pocket Jumper', price: '$34.75', type: 'women' },
    { image: '/images/product-06.jpg', quickview: 'Quick View', title: 'Vintage Inspired Classic', price: '$93.20', type: 'watches' },
    { image: '/images/product-07.jpg', quickview: 'Quick View', title: 'Shirt in Stretch Cotton', price: '$52.66', type: 'women' },
    { image: '/images/product-08.jpg', quickview: 'Quick View', title: 'Pieces Metallic Printed', price: '$18.96', type: 'women' },
    { image: '/images/product-09.jpg', quickview: 'Quick View', title: 'Converse All Star Hi Plimsolls', price: '$75.00', type: 'shoes' },
    { image: '/images/product-10.jpg', quickview: 'Quick View', title: 'Femme T-Shirt In Stripe', price: '$25.85', type: 'women' },
    { image: '/images/product-11.jpg', quickview: 'Quick View', title: 'Herschel supply', price: '$63.16', type: 'men' },
    { image: '/images/product-12.jpg', quickview: 'Quick View', title: 'Herschel supply', price: '$63.15', type: 'men' },
    { image: '/images/product-13.jpg', quickview: 'Quick View', title: 'T-Shirt with Sleeve', price: '$18.49', type: 'women' },
    { image: '/images/product-14.jpg', quickview: 'Quick View', title: 'Pretty Little Thing', price: '$54.79', type: 'women' },
    { image: '/images/product-15.jpg', quickview: 'Quick View', title: 'Mini Silver Mesh Watch', price: '$86.85', type: 'watches' },
    { image: '/images/product-16.jpg', quickview: 'Quick View', title: 'Square Neck Back', price: '$29.64', type: 'women' },
    { image: '/images/product-16.jpg', quickview: 'Quick View', title: 'Square Neck Back', price: '$29.64', type: 'bag' },
]

export type homeData = {
    image: string,
    quickview: string,
    title: string,
    price: string,
    type: string,
}

export default DATA_HOME