#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ 👷 Pre-push Check'

echo '🏗️ 👷 Checking dirties...'

git diff HEAD --quiet || (
    echo '❌ ❌ ❌ You have un-committed changes ❌ ❌ ❌';
    false;
)

echo '🏗️ 👷 Type Checking...'

yarn type || (
  echo '❌ ❌ ❌ Type check Failed ❌ ❌ ❌'
  false;
)

echo '🏗️ 👷 Building project...'

yarn build || (
  echo '❌ ❌ ❌ Build Failed ❌ ❌ ❌'
  false;
)

echo '✅ ✅ ✅ All passed. Pusing them. ✅ ✅ ✅'
